project:
  type: website
  resources:
    - LEAN_SIX_SIGMA.pdf
    - attestation_web_de_donnee.pdf
  output-dir: docs

website:
  site-url: kouamojulesquentin.github.io
  description: Mixed IC Testing - Software Engeneering -  IA
  title: "Jules Kouamo"
  open-graph: 
    locale: en_US

  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Projects"
        href: projects   
format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css



